spring:
  jpa:
    profiles: default
    show-sql: false
    hibernate:
      dialect:
        storage_engine: innodb
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

  datasource:
    url: jdbc:mysql://kis-elc-na-dev.mysql.database.azure.com/estee-na-dev?useSSL=false&autoReconnect=true&serverTimezone=UTC&useUnicode=true&character_set_server=utf8mb4
    username: kissql-admin@kis-elc-na-dev
    password: kisAbcd1234
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 100
      max-wait: 10000
      min-idle: 10
      test-on-borrow: true
      time-between-eviction-runs-millis: 300000
      max-idle: 10
      validation-query: select 1
      validation-interval: 30000
      test-while-idle: true
#
#spring.jpa.hibernate.connection.verifyServerCertificate=false
#spring.jpa.hibernate.connection.requireSSL=true
